name: Maven CI/CD Test

on:
  push:
    branches: [ main, master ] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: '20'
        distribution: 'temurin' 
        
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Navigate to Project Directory
      run: |
        cd "Social Media Analyzer"

    - name: Build with Maven
      run: mvn -B package
