name: Maven CI/CD Test

on:
  push:
    branches: [ main, master ] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    #- name: Set up JDK 1.8
    #  uses: actions/setup-java@v2
    #  with:
    #    java-version: '8'
    #    distribution: 'adopt'

    #- name: Cache Maven dependencies
    #  uses: actions/cache@v2
    #  with:
    #    path: ~/.m2
    #    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    #    restore-keys: ${{ runner.os }}-m2

    - name: Navigate to Project Directory and Echo
      run: |
        cd "Social Media Analyzer"
        echo "CI/CD test is working!"

    #- name: Build with Maven
    #  run: mvn -B package
